"""Phase 2 experiment: transcribe the test set with two Whisper models and compare.

    python 01-voicemail-triage/compare_models.py                       # small vs large-v3-turbo
    python 01-voicemail-triage/compare_models.py --models base small   # any two (or more)

For each file we check what matters downstream, not a generic accuracy score:
  - name:   does the transcript contain the caller's name from labels.json?
  - number: do the transcript's digits contain the right callback number?
  - speed:  seconds of transcription per second of audio (real-time factor).
Writes docs/transcription-comparison.md. Transcripts are cached in testset/transcripts/,
so a second run is instant and reuses the timings measured the first time.
"""

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))  # so 'shared' is importable when run as a script

from shared.transcribe import transcribe  # noqa: E402

TESTSET = HERE / "testset"
CACHE_DIR = TESTSET / "transcripts"
REPORT = ROOT / "docs" / "transcription-comparison.md"


def words(text: str) -> str:
    """Lowercase, punctuation removed, single spaces: 'Thompson,' and 'thompson' compare equal."""
    return " ".join(re.sub(r"[^\w\s]", " ", text.lower()).split())


def name_found(name: str | None, text: str) -> bool | None:
    """None when there is no name to find (label is null)."""
    if name is None:
        return None
    return f" {words(name)} " in f" {words(text)} "


def number_found(number: str | None, text: str) -> bool | None:
    """Keep only the digits of the transcript and look for the labelled number in them.

    '07700 900123', '07700-900-123' and '0 7 7 0 0 9 0 0 1 2 3' all count. This is a
    transcription check only: picking the right number when there are two is Phase 3's job.
    """
    if number is None:
        return None
    return number in re.sub(r"\D", "", text)


def mark(result: bool | None) -> str:
    return {True: "yes", False: "**NO**", None: "-"}[result]


def evaluate(model: str, labels: list[dict]) -> list[dict]:
    rows = []
    for i, label in enumerate(labels, start=1):
        t = transcribe(TESTSET / "audio" / label["file"], cache_dir=CACHE_DIR, model=model)
        rows.append({
            "id": label["id"], "label": label, "transcript": t,
            "name": name_found(label["caller_name"], t.text),
            "number": number_found(label["callback_number"], t.text),
        })
        print(f"  [{i:2}/{len(labels)}] {label['id']:32} {t.transcribe_s:5.1f}s")
    return rows


def score(rows: list[dict], key: str) -> str:
    checked = [r[key] for r in rows if r[key] is not None]
    return f"{sum(checked)}/{len(checked)}"


def build_report(results: dict[str, list[dict]]) -> str:
    models = list(results)
    out = ["# Transcription comparison (Phase 2)", "",
           "Generated by `01-voicemail-triage/compare_models.py` on the synthetic test set "
           "(fictional callers and numbers). CPU, int8.", "",
           "## Summary", "",
           "| model | names found | numbers found | audio | transcription time | real-time factor |",
           "|---|---|---|---|---|---|"]
    for m, rows in results.items():
        audio = sum(r["transcript"].duration_s for r in rows)
        spent = sum(r["transcript"].transcribe_s for r in rows)
        out.append(f"| {m} | {score(rows, 'name')} | {score(rows, 'number')} | {audio:.0f}s "
                   f"| {spent:.0f}s | {spent / audio:.2f} |")
    out += ["", "Real-time factor = transcription time / audio length. 0.10 means 1 minute of audio takes 6 s.",
            "", "## Per file", "",
            "| id | " + " | ".join(f"{m} name | {m} number" for m in models) + " |",
            "|---|" + "---|---|" * len(models)]
    for i, first in enumerate(results[models[0]]):
        cells = [f"{mark(results[m][i]['name'])} | {mark(results[m][i]['number'])}" for m in models]
        out.append(f"| {first['id']} | " + " | ".join(cells) + " |")

    out += ["", "## Misses: what the model actually wrote", ""]
    any_miss = False
    for m, rows in results.items():
        for r in rows:
            if r["name"] is False or r["number"] is False:
                any_miss = True
                lab = r["label"]
                out += [f"**{m} / {r['id']}** (expected name `{lab['caller_name']}`, "
                        f"number `{lab['callback_number']}`)", "", f"> {r['transcript'].text}", ""]
    if not any_miss:
        out.append("None.")
    return "\n".join(out) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--models", nargs="+", default=["small", "large-v3-turbo"])
    args = parser.parse_args()

    labels = json.loads((TESTSET / "labels.json").read_text(encoding="utf-8"))["items"]
    results = {}
    for model in args.models:
        print(f"Model {model}:")
        results[model] = evaluate(model, labels)

    REPORT.write_text(build_report(results), encoding="utf-8")
    for m, rows in results.items():
        print(f"{m:16} names {score(rows, 'name'):6} numbers {score(rows, 'number')}")
    print(f"Report: {REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
