"""Part 2, Phase 2 experiment: Whisper model x name hint on the meeting series.

    python 02-meeting-action-agent/compare_transcription.py
    python 02-meeting-action-agent/compare_transcription.py --configs small small+hint

Config = <whisper model>[+hint]. "+hint" passes context.whisper_hint() (team, customers, streets)
as Whisper's initial prompt. For each config and meeting we measure, against scripts.json:
  - WER:            word error rate of the whole transcript (lower is better)
  - names:          team / customer / street names that survived, counted per occurrence
  - task words:     mentions whose task can still be recognised (every match-rule group has a word
                    in the transcript): the words extraction will need in Phase 3
  - speed:          real-time factor (transcription seconds / audio seconds)
Writes docs/part2-transcription-comparison.md. Transcripts are cached in testset/transcripts/.
"""

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "testset"))

import answer_key  # noqa: E402
import context  # noqa: E402
from shared.evaluation import norm_text, pct, word_errors  # noqa: E402
from shared.transcribe import transcribe  # noqa: E402

TESTSET = HERE / "testset"
REPORT = ROOT / "docs" / "part2-transcription-comparison.md"
TTS_SPELLINGS = {"Preeya": "Priya", "Shiv awn": "Siobhan"}  # scripts.json spells some names for Piper
NAMES = context.TEAM + ["Siobhan", "Gallagher", "Margaret", "Ellis", "Dave"] + context.PLACES


def reference_text(meeting: dict) -> str:
    """What was actually said, with the real spellings."""
    text = " ".join(turn_text for _, turn_text in meeting["turns"])
    for tts, real in TTS_SPELLINGS.items():
        text = text.replace(tts, real)
    return text


def count_word(phrase: str, text: str) -> int:
    return len(re.findall(rf"\b{re.escape(phrase.lower())}\b", norm_text(text)))


def name_hits(reference: str, hypothesis: str) -> tuple[int, int]:
    """(names found, names said): per occurrence, so 'Priya' said 4 times and heard twice = 2/4."""
    said = {n: count_word(n, reference) for n in NAMES}
    heard = {n: count_word(n, hypothesis) for n in NAMES}
    return sum(min(said[n], heard[n]) for n in NAMES), sum(said.values())


def recoverable(mentions: list[dict], tasks: dict, hypothesis: str) -> int:
    """Mentions whose task's match-rule groups each have a word somewhere in the meeting's transcript.

    Same matching as the answer key (answer_key.matches). Only the 'all' groups: a whole meeting
    always contains other tasks' words, so the 'none' list would wrongly reject it.
    """
    return sum(answer_key.matches({"all": tasks[m["task"]]["match"]["all"]}, hypothesis) for m in mentions)


def run_config(config: str, meetings: list[dict], labels: dict) -> dict:
    model, _, flag = config.partition("+")
    hint = context.whisper_hint() if flag == "hint" else None
    totals = {"edits": 0, "words": 0, "names": 0, "names_said": 0, "recoverable": 0, "mentions": 0,
              "audio": 0.0, "spent": 0.0, "texts": {}}
    by_id = {m["id"]: m for m in labels["meetings"]}
    for meeting in meetings:
        label = by_id[meeting["id"]]
        t = transcribe(TESTSET / "audio" / label["file"], cache_dir=TESTSET / "transcripts", model=model, hint=hint)
        ref = reference_text(meeting)
        edits, words = word_errors(ref, t.text)
        found, said = name_hits(ref, t.text)
        totals["edits"] += edits
        totals["words"] += words
        totals["names"] += found
        totals["names_said"] += said
        totals["recoverable"] += recoverable(label["mentions"], labels["tasks"], t.text)
        totals["mentions"] += len(label["mentions"])
        totals["audio"] += t.duration_s
        totals["spent"] += t.transcribe_s
        totals["texts"][meeting["id"]] = t.text
        print(f"  {config:22} {meeting['id']}  WER {edits / words:5.1%}  names {found}/{said}  {t.transcribe_s:5.1f}s",
              flush=True)
    return totals


def build_report(results: dict[str, dict], meetings: list[dict]) -> str:
    out = ["# Part 2 transcription comparison (Phase 2)", "",
           "Generated by `02-meeting-action-agent/compare_transcription.py` on the 5-meeting synthetic series "
           "(CPU, int8, beam 5, VAD). `+hint` = Whisper initial prompt with known names only:", "",
           f"> {context.whisper_hint()}", "",
           "| config | WER | names found | task words recoverable | real-time factor |", "|---|---|---|---|---|"]
    for config, r in results.items():
        out.append(f"| {config} | {r['edits'] / r['words']:.1%} | {pct(r['names'], r['names_said'])} | "
                   f"{pct(r['recoverable'], r['mentions'])} | {r['spent'] / r['audio']:.2f} |")
    out += ["", "WER = word errors / words said (substitutions + insertions + deletions). Numbers like "
            "\"the seventh\" vs \"7th\" count as errors for every config alike.", "",
            "**Caveat:** the hint lists exactly the names that occur in these meetings, so `+hint` is a best case. "
            "In the Phase 2 review a realistic hint (11 customers, 6 streets, including look-alikes such as "
            "\"Mill Road\") gave small+hint 93 % names instead of 98 %, and once swapped in a wrong look-alike "
            "name. Still far better than no hint (71 %). Single runs: speed differences of ~15 % are noise.",
            "", "## Transcripts", ""]
    for meeting in meetings:
        out += [f"### {meeting['id']}", "", f"**said:** {reference_text(meeting)}", ""]
        out += [f"**{config}:** {r['texts'][meeting['id']]}" + "\n" for config, r in results.items()]
    return "\n".join(out) + "\n"


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser()
    parser.add_argument("--configs", nargs="+",
                        default=["small", "small+hint", "large-v3-turbo", "large-v3-turbo+hint"])
    args = parser.parse_args()

    meetings = json.loads((TESTSET / "scripts.json").read_text(encoding="utf-8"))["meetings"]
    labels = answer_key.load()
    results = {config: run_config(config, meetings, labels) for config in args.configs}
    REPORT.write_text(build_report(results, meetings), encoding="utf-8")
    for config, r in results.items():
        print(f"{config:22} WER {r['edits'] / r['words']:5.1%}  names {pct(r['names'], r['names_said'])}  "
              f"task words {pct(r['recoverable'], r['mentions'])}  RTF {r['spent'] / r['audio']:.2f}")
    print(f"Report: {REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
