"""Part 2, Phase 6: one report for the whole meeting pipeline -> docs/part2-eval-results.md.

    python 02-meeting-action-agent/evaluate.py

Reads what earlier runs saved, so it takes seconds (a missing cached transcript or extraction would be
re-made by Whisper / the LLM, which takes minutes per meeting):
  - extraction: cached results of the current prompt (testset/results/*_<PROMPT_VERSION>.json, small + hint),
    scored against labels.json: precision / recall (task only, and task + owner as in the definition of done),
    owner / due / status accuracy on matched items;
  - sync: testset/sync_runs/<items>_<sync>.json written by sync_testset.py (gold or extracted items,
    agent or rules): tracker tasks right after every meeting, spurious and duplicated rows, LLM calls, time.
Hand-written conclusions come from docs/part2-eval-notes.md and are inserted after the tables.
"""

import json
import sys
from datetime import date
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "testset"))

import answer_key  # noqa: E402
import context  # noqa: E402
from extract import PROMPT_VERSION, extract  # noqa: E402
from shared.evaluation import pct  # noqa: E402
from shared.transcribe import transcribe  # noqa: E402

TESTSET = HERE / "testset"
REPORT = ROOT / "docs" / "part2-eval-results.md"
NOTES = ROOT / "docs" / "part2-eval-notes.md"


def extraction_metrics(labels: dict) -> dict:
    """Score the cached extraction of every meeting. 'owner' = matched items with the right owner, which is
    also the count of task + owner matches used for the definition-of-done precision / recall."""
    n = {"items": 0, "mentions": 0, "pairs": 0, "owner": 0, "due": 0, "status": 0,
         "named": 0, "named_owner": 0, "seconds": 0.0}
    for meeting in labels["meetings"]:
        t = transcribe(TESTSET / "audio" / meeting["file"], cache_dir=TESTSET / "transcripts", hint=context.whisper_hint())
        r = extract(t, date.fromisoformat(meeting["date"]), cache_dir=TESTSET / "results", prompt_version=PROMPT_VERSION)
        pairs, _, _ = answer_key.match_items([i.task for i in r.items], meeting["mentions"], labels["tasks"])
        n["items"] += len(r.items)
        n["mentions"] += len(meeting["mentions"])
        n["pairs"] += len(pairs)
        n["seconds"] += r.extract_s
        for index, m in pairs:
            item = r.items[index]
            owner_ok = item.owner == m["owner"]
            n["owner"] += owner_ok
            n["due"] += (item.due.isoformat() if item.due else None) == m["due"]
            n["status"] += item.status == m["status"]
            if m.get("owner_from_text", True):
                n["named"] += 1
                n["named_owner"] += owner_ok
    return n


def load_runs() -> dict[str, dict]:
    runs = {}
    for f in sorted((TESTSET / "sync_runs").glob("*.json")):
        run = json.loads(f.read_text(encoding="utf-8"))
        runs[f"{run['items']} items / {run['sync']}"] = run
    return runs


def sync_table(runs: dict[str, dict]) -> list[str]:
    # 'left for review' matters for fairness: the agent may hand items to a human, the rules never do,
    # and the score counts a reviewed item as not done.
    out = ["| run | after m1..m5 | final tasks right | duplicated | spurious rows | left for review | LLM calls | sync time |",
           "|---|---|---|---|---|---|---|---|"]
    for name, run in runs.items():
        ms = run["meetings"]
        last = ms[-1]
        steps = " / ".join(f"{m['right']}/{m['expected']}" for m in ms)
        duplicated = sum("duplicated" in p for p in last["problems"])
        out.append(f"| {name} | {steps} | **{pct(last['right'], last['expected'])}** | {duplicated} | "
                   f"{len(last['spurious'])} | {sum(len(m['review']) for m in ms)} | {sum(m['llm_calls'] for m in ms)} | "
                   f"{sum(m['seconds'] for m in ms) / 60:.0f} min |")
    return out


def build_report(labels: dict, e: dict, runs: dict[str, dict]) -> str:
    out = ["# Part 2 evaluation results (Phase 6)", "",
           f"Generated by `02-meeting-action-agent/evaluate.py` on {date.today()}. Test set: 5 synthetic weekly meetings, "
           "28 mentions of 14 tasks (`testset/labels.json`). Whisper `small` + name hint, Ollama `qwen2.5:7b` on CPU.", "",
           f"## Extraction (prompt {PROMPT_VERSION})", "",
           "| metric | result |", "|---|---|",
           f"| precision, task only | {pct(e['pairs'], e['items'])} |",
           f"| recall, task only | {pct(e['pairs'], e['mentions'])} |",
           f"| precision, task + owner (DoD) | {pct(e['owner'], e['items'])} |",
           f"| recall, task + owner (DoD) | {pct(e['owner'], e['mentions'])} |",
           f"| owner right on matched items | {pct(e['owner'], e['pairs'])} (where the words name someone: "
           f"{pct(e['named_owner'], e['named'])}) |",
           f"| due date right on matched items | {pct(e['due'], e['pairs'])} |",
           f"| status right on matched items | {pct(e['status'], e['pairs'])} |",
           f"| LLM time per meeting (CPU) | {e['seconds'] / len(labels['meetings']):.0f} s |", "",
           "## Tracker sync", "",
           "The tracker starts empty and the five meetings are synced in order. 'gold items' = the answer key's own "
           "items (tests the sync alone); 'extracted items' = the real extraction above (tests the real pipeline). "
           "A task is right when exactly one tracker row matches it with the right owner, due date and status.", ""]
    out += sync_table(runs)
    if NOTES.exists():
        out += ["", NOTES.read_text(encoding="utf-8").strip()]
    return "\n".join(out) + "\n"


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    labels = answer_key.load()
    report = build_report(labels, extraction_metrics(labels), load_runs())
    REPORT.write_text(report, encoding="utf-8")
    print(report.split("## Conclusions")[0])
    print(f"Written: {REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
